### View results of aggregate test

In [ ]:
import pandas as pd
# import markdown
# from markdown import markdown

In [ ]:
#Change insert resume test id (csv name)
resume_id = 82246962
#fill here id above




df = pd.read_csv(f'aggregate_test_results_resumeid={resume_id}.csv')
resume_df = pd.read_csv('../data/Resume.csv')

In [55]:
#THE RESUME
r = resume_df[resume_df['ID']==resume_id]
print(r['Resume_html'].iloc[0])

<div class="fontsize fontface vmargins hmargins linespacing pagesize" id="document"> <div class="section firstsection" id="SECTION_NAME574248181" style="
      padding-top:0px;
    "> <div class="paragraph PARAGRAPH_NAME firstparagraph" id="PARAGRAPH_574248181_1_373859496" style="
      padding-top:0px;
    "> <div class="name" itemprop="name"> <span class="field fName" id="574248181FNAM1"> </span> <span> </span> <span class="field" id="574248181LNAM1"> TEST ENGINEERING</span> </div> </div> </div> <div class="section" id="SECTION_SUMM574248183" style="
      padding-top:0px;
    "> <div class="heading bottomborder"> <div class="sectiontitle" id="SECTNAME_SUMM574248183"> Profile</div> </div> <div class="paragraph firstparagraph" id="PARAGRAPH_574248183_1_373859507" style="
      padding-top:0px;
    "> <div class="field singlecolumn" id="574248183FRFM1"> I am seeking the challenging position with a technology company that will allow me to apply and enhance my skills of being Test Engineer to their fullest potential. Possessing over 10 years of experience in the electronics manufacturing and test engineering environment can bring high level of responsibility and technical role in your company. In addition, I am eager to contribute my creativity and hard work towards the success of your company and to the growth of the fast developing field.</div> </div> </div> <div class="section" id="SECTION_HILT574248184" style="
      padding-top:0px;
    "> <div class="heading bottomborder"> <div class="sectiontitle" id="SECTNAME_HILT574248184"> Areas of Expertise</div> </div> <div class="paragraph firstparagraph" id="PARAGRAPH_574248184_1_373859508" style="
      padding-top:0px;
    "> <div class="singlecolumn maincolumn"> <table class="twocol"> <tbody> <tr> <td class="field twocol_1" id="574248184SKC11"> <ul> <li> Digital/Analog and RF Circuits Design Techniques and Troubleshooting, used Agilent E5061B-3L5 LF-RF Network Analyzer for troubleshooting</li> <li> Proficient with circuit board and microscope soldering skills and rework</li> <li> Interpret in reading schematic diagram for AC/DC circuits</li> <li> View Expert CAD Design software operating experience</li> <li> TEXMAC Flying probe 9000 series program experience</li> <li> Agilent 83480A Digital Communication Analyzer operating experience</li> <li> Employment Hands on Computer Skills</li> <li> Python Scripting for test automation</li> <li> Solaris 10 OS, Linux Mandrake and Red Hat OS Configuration</li> <li> SQL Server Configuration</li> <li> UNIX Script &amp; Shell Programming</li> <li> Networking Essentials</li> <li> Networking Cabling Cat5e, Cat6 and Fiber Optic</li> <li> TCP/IP and OSI Layers Knowledge</li> <li> Windows XP Pro-Win 7 Mac OS X Leopard</li> <li> PC Hardware Installation PC Troubleshooting</li> <li> PC Software Installation Routers and Switches</li> <li> Cable Modems Experience</li> <li> Network Subnetting, routing and addressing</li> </ul> </td> <td class="field twocol_2" id="574248184SKC21"> </td> </tr> </tbody> </table> </div> </div> </div> <div class="section" id="SECTION_EXPR574248185" style="
      padding-top:0px;
    "> <div class="heading bottomborder"> <div class="sectiontitle" id="SECTNAME_EXPR574248185"> Professional Experience</div> </div> <div class="paragraph firstparagraph" id="PARAGRAPH_574248185_1_373859498" itemscope="" itemtype="https://schema.org/Organization" style="
      padding-top:0px;
    "> <div class="singlecolumn"> <span class="paddedline"> <span class="jobtitle" id="574248185JTIT1"> Test Engineering</span> <span> </span> <span class="datesWrapper"> <span class="jobdates" format="%b %Y" id="574248185JSTD1"> Feb 2006</span> <span>  to </span> <span class="jobdates" format="%b %Y" id="574248185EDDT1"> Current</span> <br/> </span> </span> <span class="paddedline" itemscope="" itemtype="https://schema.org/postalAddress"> <span class="companyname" id="574248185COMP1" itemprop="name"> Company Name</span> <span>  － </span> <span class="joblocation jobcity" id="574248185JCIT1" itemprop="addressLocality"> City</span> <span> , </span> <span class="joblocation jobstate" id="574248185JSTA1" itemprop="addressRegion"> State</span> </span> <span class="jobline" id="574248185JDES1" itemprop="description"> <ul> <li> Perform component debugging on the complex android mobile technology products with Android Debug commands.</li> <li> Bring up ongoing reliability lab for the android device compliance testing that includes tumble test, drop test, button cycling test, thermal testing and humidity environment testing.</li> <li> Troubleshoot and perform final root cause failure analysis on the component level for Riverbed Steelhead, Sturgeons, and Interceptors WAN optimization hardware appliances.</li> <li> Responsible to perform functional test and system level validation, Report directly to the customer's quality engineering department with final failure analysis data results on RMA/FA systems.</li> <li> Manage RMA returns and process orders.</li> <li> Perform incoming quality check on the RMA systems.</li> <li> Upgrade firmware or software if required.</li> <li> Use test equipment tools Digital/Analog meters, Signal Generators, Oscilloscope Tektronix TDS 3052, Fluke 26III True RMS MM meter to find root cause on the electrical circuits.</li> <li> TestExpert CAD for signal view.</li> <li> Directly work with customer's engineers to resolve all test related issues and act as primary technical customer interface.</li> <li> Prepare and develop test process procedures and disseminate test-engineering standards for developed test systems.</li> <li> Measure and control test debug WIP.</li> <li> Stay abreast of technology trends.</li> <li> Design, develop, maintain test procedures, and tester software for electronic circuit board production.</li> <li> Support junior technicians with failure analysis, tester debugging, reduction of intermittent failures.</li> <li> Review test equipment designs, data and RMA issues with customers regularly.</li> <li> Support backend production floor with BOM breakdown for Intel X-86 server platform, Created Visual Aids.</li> <li> work instructions for assemblies from frontend to backend.</li> <li> Properly implement ECO, ECN, Deviations, SPIs and ETN rework on the production floor.</li> <li> Design barcode labels with loftware design software for assemblies and subassemblies.</li> <li> Create MES routes for the assemblies and controlled process verification in the MES system.</li> <li> Bronze Six Sigma certified.</li> <li> Participate in Lean manufacturing eg.</li> <li> The 5S's, Kaizen Blitz or Events, QRQC, Workflow Analysis, Layouts &amp; workcell design, Kanban, Simulated continuous flow, De-bottlenecking, Takt Time and other process related improvements, FPY reports for test matrix, Test Debug WIP reports.</li> <li> Applied Lean Six Sigma methodologies to improve production process.</li> <li> Work with Test and Manufacturing engineering departments for DFT and developed test programs.</li> <li> Extensive experience in NPI environment and NPI process improvements, customer's NPI projects portfolio includes McAfee, Riverbed, HP, Silverspring networks, NEC, Cisco, Pocketfinder, Sunpower &amp; Sable networks.</li> <li> Traveled domestic and overseas to coach diagnostic technicians for new customers and existing customer product lines.</li> </ul> </span> </div> </div> <div class="paragraph" id="PARAGRAPH_574248185_2_373859499" itemscope="" itemtype="https://schema.org/Organization" style="
      padding-top:0px;
    "> <div class="singlecolumn"> <span class="paddedline"> <span class="jobtitle" id="574248185JTIT2"> Integration System Engineer</span> <span> </span> <span class="datesWrapper"> <span class="jobdates" format="%b %Y" id="574248185JSTD2"> Jul 2005</span> <span>  to </span> <span class="jobdates" format="%b %Y" id="574248185EDDT2"> Feb 2006</span> <br/> </span> </span> <span class="paddedline" itemscope="" itemtype="https://schema.org/postalAddress"> <span class="companyname" id="574248185COMP2" itemprop="name"> Company Name</span> <span>  － </span> <span class="joblocation jobcity" id="574248185JCIT2" itemprop="addressLocality"> City</span> <span> , </span> <span class="joblocation jobstate" id="574248185JSTA2" itemprop="addressRegion"> State</span> </span> <span class="jobline" id="574248185JDES2" itemprop="description"> <ul> <li> Responsible to create proposals, design Security Access Control, CCTV Surveillance System and Alarm Systems for Government, Commercial, and Residential customers.</li> <li> Provided Technical Support to Field Technicians and customers.</li> <li> Install GPS tracking devices on fleet vehicles.</li> </ul> </span> </div> </div> <div class="paragraph" id="PARAGRAPH_574248185_3_373859500" itemscope="" itemtype="https://schema.org/Organization" style="
      padding-top:0px;
    "> <div class="singlecolumn"> <span class="paddedline"> <span class="jobtitle" id="574248185JTIT3"> Lab Technician</span> <span> </span> <span class="datesWrapper"> <span class="jobdates" format="%b %Y" id="574248185JSTD3"> Apr 2003</span> <span>  to </span> <span class="jobdates" format="%b %Y" id="574248185EDDT3"> Jul 2005</span> <br/> </span> </span> <span class="paddedline" itemscope="" itemtype="https://schema.org/postalAddress"> <span class="companyname" id="574248185COMP3" itemprop="name"> Company Name</span> <span>  － </span> <span class="joblocation jobcity" id="574248185JCIT3" itemprop="addressLocality"> City</span> <span> , </span> <span class="joblocation jobstate" id="574248185JSTA3" itemprop="addressRegion"> State</span> </span> <span class="jobline" id="574248185JDES3" itemprop="description"> <ul> <li> Work directly with the company's Vice President of engineering on the development of alarm verification VIT system.</li> <li> Support development of new production and R&amp;D engineering department overseas with BOM breakdown, Visual Aids, Schematics improvements and US FCC compliance requirements.</li> <li> Daily job duties included test and Troubleshoot CCTV Security products.</li> <li> Performed electrical conformance testing with Agilent 83480A Digital Communication Analyzer.</li> <li> Introduce new product lines to the customer and marketing department.</li> <li> Provided Technical Support on all company products on phone and via email.</li> </ul> </span> </div> </div> <div class="paragraph" id="PARAGRAPH_574248185_4_373859501" itemscope="" itemtype="https://schema.org/Organization" style="
      padding-top:0px;
    "> <div class="singlecolumn"> <span class="paddedline"> <span class="jobtitle" id="574248185JTIT4"> Test Technician III</span> <span> </span> <span class="datesWrapper"> <span class="jobdates" format="%b %Y" id="574248185JSTD4"> Jan 2002</span> <span>  to </span> <span class="jobdates" format="%b %Y" id="574248185EDDT4"> Mar 2003</span> <br/> </span> </span> <span class="paddedline" itemscope="" itemtype="https://schema.org/postalAddress"> <span class="companyname" id="574248185COMP4" itemprop="name"> Company Name</span> <span>  － </span> <span class="joblocation jobcity" id="574248185JCIT4" itemprop="addressLocality"> City</span> <span> , </span> <span class="joblocation jobstate" id="574248185JSTA4" itemprop="addressRegion"> State</span> </span> <span class="jobline" id="574248185JDES4" itemprop="description"> <ul> <li> Test and troubleshoot flat touch screens and report daily test reports to engineering department.</li> <li> Trained new employees to perform task on assembly lines.</li> </ul> </span> </div> </div> <div class="paragraph" id="PARAGRAPH_574248185_5_373859502" itemscope="" itemtype="https://schema.org/Organization" style="
      padding-top:0px;
    "> <div class="singlecolumn"> <span class="paddedline"> <span class="jobtitle" id="574248185JTIT5"> Production Test Technician II</span> <span> </span> <span class="datesWrapper"> <span class="jobdates" format="%b %Y" id="574248185JSTD5"> Oct 2000</span> <span>  to </span> <span class="jobdates" format="%b %Y" id="574248185EDDT5"> Nov 2001</span> <br/> </span> </span> <span class="paddedline" itemscope="" itemtype="https://schema.org/postalAddress"> <span class="companyname" id="574248185COMP5" itemprop="name"> Company Name</span> <span>  － </span> <span class="joblocation jobcity" id="574248185JCIT5" itemprop="addressLocality"> City</span> <span> , </span> <span class="joblocation jobstate" id="574248185JSTA5" itemprop="addressRegion"> State</span> </span> <span class="jobline" id="574248185JDES5" itemprop="description"> <ul> <li> Certified WWOPS Final Analysis Manufactured Training.</li> <li> Ability to Test and Debugged all SUNFIRE mid and high series servers.</li> <li> Generate daily work report on failed CPU boards and other components.</li> <li> Experience in Assembly line, Kitting and pack out.</li> <li> Assisted Manufacturing Engineers to installed and tested new features on a servers.</li> <li> Interpret and very familiar with SUN Microsystems technical docs on Netscape interanet.</li> </ul> </span> </div> </div> <div class="paragraph" id="PARAGRAPH_574248185_6_373859503" itemscope="" itemtype="https://schema.org/Organization" style="
      padding-top:0px;
    "> <div class="singlecolumn"> <span class="paddedline"> <span class="jobtitle" id="574248185JTIT6"> Test Technician I</span> <span> </span> <span class="datesWrapper"> <span class="jobdates" format="%b %Y" id="574248185JSTD6"> Mar 1999</span> <span>  to </span> <span class="jobdates" format="%b %Y" id="574248185EDDT6"> Sep 2000</span> <br/> </span> </span> <span class="paddedline" itemscope="" itemtype="https://schema.org/postalAddress"> <span class="companyname" id="574248185COMP6" itemprop="name"> Company Name</span> <span>  － </span> <span class="joblocation jobcity" id="574248185JCIT6" itemprop="addressLocality"> City</span> <span> , </span> <span class="joblocation jobstate" id="574248185JSTA6" itemprop="addressRegion"> State</span> </span> <span class="jobline" id="574248185JDES6" itemprop="description"> <ul> <li> Directly work with Engineers on new customer products for Telecommunication Servers.</li> <li> Performed test and repaired bad main boards, worked on SMT machines on a production.</li> </ul> </span> </div> </div> </div> <div class="section" id="SECTION_EDUC574248186" style="
      padding-top:0px;
    "> <div class="heading bottomborder"> <div class="sectiontitle" id="SECTNAME_EDUC574248186"> Education</div> </div> <div class="paragraph firstparagraph" id="PARAGRAPH_574248186_1_373859504" itemscope="" itemtype="https://schema.org/EducationalOrganization" style="
      padding-top:0px;
    "> <div class="singlecolumn"> <span class="paddedline" itemprop="description"> <span class="degree" id="574248186DGRE1" itemprop="name"> BSEE</span> <span class="programline" id="574248186STUY1"> </span> <span class="datesWrapper"> <span class="jobdates" id="574248186GRYR1"> 2016</span> </span> </span> <span class="paddedline"> <span class="companyname companyname_educ" id="574248186SCHO1" itemprop="name"> Northwestern Polyphonic University</span> <span>  － </span> <span class="joblocation jobcity" id="574248186SCIT1"> City</span> <span> , </span> <span class="joblocation jobstate" id="574248186SSTA1"> State</span> <span class="joblocation jobstate" id="574248186SCNT1"> </span> </span> <span class="field" id="574248186FRFM1"> </span> </div> </div> <div class="paragraph" id="PARAGRAPH_574248186_2_373859506" itemscope="" itemtype="https://schema.org/EducationalOrganization" style="
      padding-top:0px;
    "> <div class="singlecolumn"> <span class="paddedline" itemprop="description"> <span class="degree" id="574248186DGRE2" itemprop="name"> Associate Degree</span> <span> , </span> <span class="programline" id="574248186STUY2"> Physics, Chemistry and Mathematics</span> <span class="datesWrapper"> <span class="jobdates" id="574248186GRYR2"> 2001</span> </span> </span> <span class="paddedline"> <span class="companyname companyname_educ" id="574248186SCHO2" itemprop="name"> D.A.V. College Jalandhar City</span> <span class="joblocation jobcity" id="574248186SCIT2"> </span> <span class="joblocation jobstate" id="574248186SSTA2"> </span> <span class="joblocation jobstate" id="574248186SCNT2"> </span> </span> <span class="paddedline"> <span> GPA: </span> <span class="field" id="574248186GRPA2"> GPA: 4.0</span> </span> <span class="field" id="574248186FRFM2"> GPA: 4.0</span> </div> </div> <div class="paragraph" id="PARAGRAPH_574248186_3_373859505" itemscope="" itemtype="https://schema.org/EducationalOrganization" style="
      padding-top:0px;
    "> <div class="singlecolumn"> <span class="paddedline" itemprop="description"> <span class="degree" id="574248186DGRE3" itemprop="name"> AAS Degree</span> <span> , </span> <span class="programline" id="574248186STUY3"> Electronics Technology</span> </span> <span class="paddedline"> <span class="companyname companyname_educ" id="574248186SCHO3" itemprop="name"> Heald College School of Technology</span> <span>  － </span> <span class="joblocation jobcity" id="574248186SCIT3"> City</span> <span> , </span> <span class="joblocation jobstate" id="574248186SSTA3"> State</span> <span class="joblocation jobstate" id="574248186SCNT3"> </span> </span> <span class="field" id="574248186FRFM3"> Electronics Technology</span> </div> </div> </div> <div class="section" id="SECTION_AFIL574248187" style="
      padding-top:0px;
    "> </div> <div class="section" id="SECTION_SKLL574248188" style="
      padding-top:0px;
    "> <div class="heading bottomborder"> <div class="sectiontitle" id="SECTNAME_SKLL574248188"> Skills</div> </div> <div class="paragraph firstparagraph" id="PARAGRAPH_574248188_1_373859509" style="
      padding-top:0px;
    "> <div class="field singlecolumn" id="574248188FRFM1"> Assembly, automation, Cable Modems, Cabling, CAD, Cat5, Cisco, coach, hardware, CPU, DC, debugging, DFT, Design software, electronics, email, features, functional, Government, GPS, HP, Intel, Linux, Logic Analyzer, Mac OS, marketing, McAfee, MES, Access, Win 7, Windows XP, NEC, Netscape, Network, Networking, Networking Essentials, networks, OS, optimization, Oscilloscope, OSI, PC Hardware Installation, PC Software, PC Troubleshooting, proposals, Python, quality, reading, Red Hat, RMS, Routers, routing, Schematics, Servers, Shell Programming, Script, Scripting, Signal Generators, Six Sigma, Solaris, soldering, SQL Server, SUN Microsystems, Switches, TCP/IP, TDS, Technical Support, Telecommunication, phone, test equipment, Troubleshoot, Troubleshooting, UNIX, Upgrade, validation, View, WAN, Workflow Analysis, X-86</div> </div> </div> </div>

In [56]:
df.head(10)

,Unnamed: 0,tfidf_job_index,tfidf_job_descriptions,tfidf_scores,keyword_matching_job_index,keyword_matching_job_descriptions,keyword_matching_scores,encoder_job_index,encoder_job_descriptions,encoder_scores
0,0,1435,Job Title: Software Engineer\nJob Location: Ba...,0.647367,0,We are looking for hire experts flutter develo...,4,361,Job Summary*\nThe Network Engineer (Test Lab) ...,[0.6631317]
1,1,1172,"For over 10 years, Zscaler has been disrupting...",0.641820,1521,Company Description\n\nGuestTek™ is a global l...,4,1736,We are looking looking for exceptionally talen...,[0.63628995]
2,2,607,Amazon's Employee Services Tech (ES Tech) team...,0.638368,1515,JD for Software Engineer\nLocation-Hinjawadi P...,4,507,*Job Summary*\nJob Description\n*Job Summary*\...,[0.6342023]
3,3,1473,"Company Profile\nAt Morgan Stanley, we advise,...",0.625893,1516,The project duration is 15 days\nBudget - 10k\...,4,463,*Job Summary*\nJob Description\n*Job Summary*\...,[0.6342023]
4,4,431,17791 DevOps Engineer II (Open)\n\nPosition Ty...,0.618600,1517,Job Description*\nWe are looking for a PHP Dev...,4,2163,looking for computer engineer freshers can als...,[0.63246024]
5,5,1991,Description\n\nPrimary Responsibilities\n\nDes...,0.615163,1518,Greeting to All :\nWe are an IT Company Based ...,4,1172,"For over 10 years, Zscaler has been disrupting...",[0.6270292]
6,6,1400,"Overview\n\n\nBased in Silicon Valley, Tintri ...",0.612681,1519,Qualification\n\nEducation Specialisation Deta...,4,343,Responsibilities:\nThe Software Engineer in te...,[0.6192639]
7,7,163,Staff - Software Development Engineer in Test\...,0.611147,1520,Yo Corp. is a data communications and security...,4,1429,seeking experienced senior full stack engineer...,[0.61639154]
8,8,275,Neustar is an information services and technol...,0.609187,1522,"Roles & Responsibilities:\nWrite clean, mainta...",4,779,Job Title\nSoftware Engineer I\nJob Descriptio...,[0.6130575]
9,9,1411,Job Requisition ID #\n20WD40430\n\nCloud DevOp...,0.606143,1513,Node JS Location: Chennai (Greams Road) Skills...,4,595,Required Network Engineer with Knowledge of Ha...,[0.607958]

In [60]:
best_job_ids = df[['tfidf_job_index','keyword_matching_job_index','encoder_job_index']]
best_job_ids

   tfidf_job_index  keyword_matching_job_index  encoder_job_index
0             1435                           0                361
1             1172                        1521               1736
2              607                        1515                507
3             1473                        1516                463
4              431                        1517               2163
5             1991                        1518               1172
6             1400                        1519                343
7              163                        1520               1429
8              275                        1522                779
9             1411                        1513                595

In [73]:
#in both tfidf and encoder
[x for x in list(best_job_ids['tfidf_job_index']) if x in list(best_job_ids['encoder_job_index'])]

[1172]

In [74]:
tfidf = df.iloc[:,1:4]
tfidf

,tfidf_job_index,tfidf_job_descriptions,tfidf_scores
0,1435,Job Title: Software Engineer\nJob Location: Ba...,0.647367
1,1172,"For over 10 years, Zscaler has been disrupting...",0.641820
2,607,Amazon's Employee Services Tech (ES Tech) team...,0.638368
3,1473,"Company Profile\nAt Morgan Stanley, we advise,...",0.625893
4,431,17791 DevOps Engineer II (Open)\n\nPosition Ty...,0.618600
5,1991,Description\n\nPrimary Responsibilities\n\nDes...,0.615163
6,1400,"Overview\n\n\nBased in Silicon Valley, Tintri ...",0.612681
7,163,Staff - Software Development Engineer in Test\...,0.611147
8,275,Neustar is an information services and technol...,0.609187
9,1411,Job Requisition ID #\n20WD40430\n\nCloud DevOp...,0.606143

In [75]:
print(  tfidf.loc[1, 'tfidf_job_descriptions']   )

For over 10 years, Zscaler has been disrupting and transforming the security industry. Our 100% purpose-built cloud platform delivers the entire gateway security stack as a service through 150 global data centers to securely connect users to their applications, regardless of device, location, or network in over 185 countries protecting over 3,900 companies and have detected 100 Million threats/day.

We work in a fast-paced, dynamic and make it happen culture. Our people are some of the brightest and passionate in the industry that thrives on being the first to solve problems. We are always looking to hire highly passionate, collaborative and humble people that want to make a difference.

The Emerging Technology group is a fast paced and exciting product development team which is at the forefront of adopting cloud technology and solving customer problems. We hire talented engineers and provide them lots of freedom and autonomy to build great products. The position is to hire an engineer who will contribute to significantly improve product quality. We are looking for engineers with a combination of
solid in-depth understanding of networking, systems and security and have the ability to test software for scale, performance and availability.

Role- Devtest Engineer

Location- Chandigarh/Mohali

Our ideal candidate is willing to learn new skillsets and take on challenges.

Responsibilities/What You’ll Do:

• Work closely with Developers, QA, and others to understand new features, use cases, and customer scenarios.
• Participate in design and implementation of test infrastructure to support moving services to a Continuous Deployment
• Develop white box testing strategy and implement test/scripts for high availability, scale and performance
• Work with the QA team to complement their testing
• Help reproduce production bugs in various lab environments and report
accordingly (JIRA, Bugzilla, Mantis).
• Responsible for releasing product features to QA using a combination of manual and auto-testing techniques.
• Follow internal development, test and build processes.
• Create maintain, enhance and execute test cases as part of dev readiness for the product/features.
• Identify, document, and track software defects found during testing.
• Write and maintain automation scripts.

 3+ years’ experience working on systems, or/and distributed systems with focus on networking/firewall technologies.
 A BS/MS degree in computer science or related field.
 Solid C coding skills and good hands on developing automation and white box testing.
 Solid understanding of TCP/IP protocol stack, http, dnS and other related
protocols and products (DNS, DHCP, VPN, HA, routing and switching)
 Good Understanding of security technologies like firewall, IPS, Authentication,VPN etc.
 Experience with Unix/Linux operating system at kernel/user level.
 Strong software design, profiling, and verification skills

Qualifications/Your Background:

 Experience with open source tools and resources.
 Comfort and familiarity with common data structures, algorithms and collections.
 Working experience in Software Dev test and testing methodologies.
 3+ years’ experience with testing “systems” products (network analytics,
networking, virtualization, etc.)
 Knowledge of general QA procedures and methodologies, as well as software development fundamentals
 Demonstrated skills in scripting languages, such as shell and Python a plus
 Working experience with REST APIs.
 Outstanding written and verbal communication skills.
 Self-motivated, a strong team player.
 Excellent communication, collaboration, reporting, analytical and problem
solving skills

It would be great if you have:

 Experience in using Spirent or Ixia traffic generator is a plus
 Experience looking at packet captures and in handling customer issues and trouble-shooting
 Ability to analyze the root cause and optimize the test scripts for test automation
 Experience working with large data sets
 Experience configuring, installing, and troubleshooting server software and hardware in a Windows and Unix environment
 Experience working with DPDK platform other technologies for packet processing
 Experience in a CI-CD environment.

Why Zscaler?

Zscaler is the world’s leading software-as-a-service security platform
We deliver best of breed security services with unprecedented scale
100 Million threats detected a day across 185+ countries
Glassdoor rating of 4.7/5.0 + 98% CEO Approval = Exceptional place to work!

People who excel at Zscaler are smart, motivated and share our values. Ask yourself: Do you want to team with the best talent in the industry? Do you want to work on disruptive technology? Do you thrive in a fluid work environment? Do you appreciate a company culture that enables individual and group success and celebrates achievement? If you said yes, we’d love to talk to you about joining our award-winning team.

Learn more at zscaler.com or follow us on Twitter @zscaler. Additional information about Zscaler (NASDAQ: ZS ) is available at http://www.zscaler.com. All qualified applicants will receive consideration for employment without regard to race, sex, color, religion, sexual orientation, gender identity, national origin, protected veteran status, or on the basis of disability.

#LI-VK1

In [11]:
key_words = df.iloc[:,4:7]
key_words

,keyword_matching_job_index,keyword_matching_job_descriptions,keyword_matching_scores
0,0,We are looking for hire experts flutter develo...,5
1,1521,Company Description\n\nGuestTek™ is a global l...,5
2,1515,JD for Software Engineer\nLocation-Hinjawadi P...,5
3,1516,The project duration is 15 days\nBudget - 10k\...,5
4,1517,Job Description*\nWe are looking for a PHP Dev...,5
5,1518,Greeting to All :\nWe are an IT Company Based ...,5
6,1519,Qualification\n\nEducation Specialisation Deta...,5
7,1520,Yo Corp. is a data communications and security...,5
8,1522,"Roles & Responsibilities:\nWrite clean, mainta...",5
9,1513,Node JS Location: Chennai (Greams Road) Skills...,5

In [48]:
print(  key_words.loc[4, 'keyword_matching_job_descriptions']   )

Job Description*
We are looking for a PHP Developer responsible for managing back-end services and the interchange of data between the server and the users. Your primary focus will be the development of all server-side logic, definition and maintenance of the central database, and ensuring high performance and responsiveness to requests from the front-end.
PHP Developer duties and responsibilities*
Develop, record and maintain cutting edge web-based PHP applications on portal plus premium service platforms
Build innovative, state-of-the-art applications and collaborate with the User Experience (UX) team
Ensure HTML, CSS, and shared JavaScript is valid and consistent across applications
Prepare and maintain all applications utilizing standard development tools
Utilize backend data services and contribute to increase existing data services API
Lead the entire web application development life cycle right from concept stage to delivery and post launch support
Refactor, optimize and improve the existing codebase for maintenance and scale
Use test driven development and acceptance tests to ensure feature quality
Interface with customer and internal teams to gather requirements and develop software solutions
Convey effectively with all task progress, evaluations, suggestions, schedules along with technical and process issues
Document the development process, architecture, and standard components
PHP Developer requirements and qualifications*
Previous working experience as a PHP Developer for 3 years
BS/MS in Computer Science, Engineering or a similar relevant field
User authentication and authorization between multiple systems, servers, and environments
Integration of multiple data sources and databases into one system
Familiarity with limitations of PHP as a platform and its workarounds
Proficient in PHP, HTML5, JavaScript, JQuery Expert
Experience with PHP MVC frameworks ,CodeIgniter,
Extensive experience with Search Engine Optimization (SEO).
Hands on Angular and couchDB
Excellent relational database skills with MySQL
Experience with building restful JSON web services
Knowledge of API's, such as twitter, Facebook, Google maps, Instagram, etc.
Understanding of responsive design frameworks such as bootstrap
Job Type: Contract

Job Type: Contract

Experience:
total work: 3 years (Preferred)
Education:
Bachelor's (Required)
Programming Languages needed:
PHP (Required)
Work Remotely:
Yes

In [12]:
encoder = df.iloc[:,7:10]
encoder

,encoder_job_index,encoder_job_descriptions,encoder_scores
0,1305,main responsibility hr administrator mainly ad...,[0.49065423]
1,517,resident administrator responsible administrat...,[0.4840711]
2,2225,qualification required qualification high scho...,[0.47433412]
3,2069,graduation bachelor ’ degree accredited colleg...,[0.46638045]
4,2041,position summary art science seeking dynamic d...,[0.46185827]
5,1205,project coordinator san jose/evergreen communi...,[0.45047]
6,1454,office administrator global local total nation...,[0.45012635]
7,213,job code 403033 staff assistant iii duty & res...,[0.44600058]
8,335,administrative secretary position number 99383...,[0.44148213]
9,1394,Basic Qualifications :\n\nBachelor's degree in...,[0.43823946]

project coordinator san jose/evergreen community college district position 1800072 required document 1\ letter introduction cover letter 2\ resume 3\ copy transcript associate 's degree equivalent department facility & bond program management posting date 07/31/2018 first review date 08/14/2018 position status full-time salary range $ 60632 - $ 74011 annual salary range 96 classified salary schedule fiscal year 2017-2018 starting placement generally step 1 benefit available - classified excellent fringe benefit package includes district paid medical dental vision eap employee assistance plan life insurance employee eligible dependent income protection voluntary plan include supplemental life insurance flexible spending account 403b 457 deferred compensation account classified employee also receive vacation sick leave 18 paid holiday employment start date soon possible position summary program coordinator report director facility bond program district office work schedule 12 month per year ; monday - friday ; 8:00 a.m. 5:00 p.m position represented california school employee association csea chapter 363 position purpose direction director facility bond program management assigned administrator project coordinator performs wide range complex clerical standard advanced office support duty management bond capital outlay program position coordinate various communication activity among administrator department staff vendor consultant public duty responsibilities/specific position 1\ perform appropriate administrative operation support duty assigned supervisor relieve variety technical administrative detail may provide support dept manager staff member 2\ coordinate liaison dept college administrator faculty staff architect engineer consultant ; coordinate activity group preparation project design drawing specification 3\ maintain accurate detailed calendar event due date schedule relate assigned area service ensure proper task activity occur scheduled 4\ prepare meeting agenda minute construction schedule update construction management consultant required project/construction management bond executive meeting 5\ assist onsite coordination move construction project coordinate construction manager faculty staff purchasing personnel necessary 6\ assist preparation departmental report gathering organizing summarizing information variety source including submittals update california community college chancellor 's office fusion database 7\ track project budget activity assist resolving department budget issue problem coordinate timesheets monitor expenditure related bond project 8\ maintain organize facility department network physical information storage system ; ensure required document received logged district record 9\ update construction communication keeping information current community district needed 10\ support vendor outreach effort accordance board policy 11\ prepare compose formal correspondence various agency architect firm college department community required 12\ perform related duty assigned employment standard knowledge 1\ modern office method equipment including computer terminal micro- computer usage word processing application 2\ facility project construction management software system 3\ record keeping principle procedure ; business accounting mathematics ; acceptable business office etiquette 4\ organization time management standard office procedure ability 1\ read interpret apply explain district policy procedure regulation 2\ utilize exceptional organizational skill dealing ambiguity change 3\ establish review work priority ; work independently follow task 4\ compile information write report business correspondence procedure manual using correct english grammar spelling punctuation vocabulary 5\ exhibit strong sense urgency regarding work progress project 6\ effectively communicate interact person diverse background ability 7\ establish maintain cooperative working relationship contacted course work minimum qualification education experience 1\ associate 's degree accredited institution preferably business construction management related field 2\ three year administrative support experience involving heavy public contact primary support individual department preferably public sector 3\ demonstrated sensitivity knowledge understanding diverse academic socioeconomic gender gender identity cultural disability ethnic background student serve ; sensitivity knowledge understanding group historically underrepresented group may experienced discrimination 4\ success integrating diversity appropriate major duty outlined job description duty listed district 's hiring policy ; demonstrated equivalent transferable skill working condition environment 1\ typical office environment physical demand 1\ requires sufficient hand-eye-arm coordination use keyboard plus arm/hand movement retrieve work material operate variety general office equipment requires visual acuity read word number requires auditory ability carry conversation phone person san jose/evergreen community college district - classified district represented dedicated talented employee passionate providing student population best educational experience possible district recognizes cultural diversity academic environment promotes academic excellence ; foster cultural racial human understanding ; provides positive role model student creates inclusive supportive educational work environment employee student community serf fall 2017 enrollment approximately 18500 per semester extremely diverse student population hispanic/latino 44 black/african- american 4 asian/pacific islander 32 american indian/native american 0.5 white/caucasian 11 attaining educational goal reflecting 45 - aa degree transfer 4-year college/ university district 's emphasis student success make recognized educational leader state district encourages diverse pool applicant serve colleague existing diverse classified staff consisting 41 hispanic/latino 26 asian/pacific islander 5 black/african american 1 american indian/native american 22 white/caucasian well encouraging application qualified outstanding applicant full application instruction position description visit http //www.edjoin.org/home/jobposting/1079042 copyright ©2017 jobelephant.com inc. right reserved posted free value-added recruitment advertising agency jeid-49be3beb5cf49e46beb2376be8e1a494

In [44]:
print(  encoder.loc[5, 'encoder_job_descriptions']   )

project coordinator san jose/evergreen community college district position 1800072 required document 1\ letter introduction cover letter 2\ resume 3\ copy transcript associate 's degree equivalent department facility & bond program management posting date 07/31/2018 first review date 08/14/2018 position status full-time salary range $ 60632 - $ 74011 annual salary range 96 classified salary schedule fiscal year 2017-2018 starting placement generally step 1 benefit available - classified excellent fringe benefit package includes district paid medical dental vision eap employee assistance plan life insurance employee eligible dependent income protection voluntary plan include supplemental life insurance flexible spending account 403b 457 deferred compensation account classified employee also receive vacation sick leave 18 paid holiday employment start date soon possible position summary program coordinator report director facility bond program district office work schedule 12 month per year ; monday - friday ; 8:00 a.m. 5:00 p.m position represented california school employee association csea chapter 363 position purpose direction director facility bond program management assigned administrator project coordinator performs wide range complex clerical standard advanced office support duty management bond capital outlay program position coordinate various communication activity among administrator department staff vendor consultant public duty responsibilities/specific position 1\ perform appropriate administrative operation support duty assigned supervisor relieve variety technical administrative detail may provide support dept manager staff member 2\ coordinate liaison dept college administrator faculty staff architect engineer consultant ; coordinate activity group preparation project design drawing specification 3\ maintain accurate detailed calendar event due date schedule relate assigned area service ensure proper task activity occur scheduled 4\ prepare meeting agenda minute construction schedule update construction management consultant required project/construction management bond executive meeting 5\ assist onsite coordination move construction project coordinate construction manager faculty staff purchasing personnel necessary 6\ assist preparation departmental report gathering organizing summarizing information variety source including submittals update california community college chancellor 's office fusion database 7\ track project budget activity assist resolving department budget issue problem coordinate timesheets monitor expenditure related bond project 8\ maintain organize facility department network physical information storage system ; ensure required document received logged district record 9\ update construction communication keeping information current community district needed 10\ support vendor outreach effort accordance board policy 11\ prepare compose formal correspondence various agency architect firm college department community required 12\ perform related duty assigned employment standard knowledge 1\ modern office method equipment including computer terminal micro- computer usage word processing application 2\ facility project construction management software system 3\ record keeping principle procedure ; business accounting mathematics ; acceptable business office etiquette 4\ organization time management standard office procedure ability 1\ read interpret apply explain district policy procedure regulation 2\ utilize exceptional organizational skill dealing ambiguity change 3\ establish review work priority ; work independently follow task 4\ compile information write report business correspondence procedure manual using correct english grammar spelling punctuation vocabulary 5\ exhibit strong sense urgency regarding work progress project 6\ effectively communicate interact person diverse background ability 7\ establish maintain cooperative working relationship contacted course work minimum qualification education experience 1\ associate 's degree accredited institution preferably business construction management related field 2\ three year administrative support experience involving heavy public contact primary support individual department preferably public sector 3\ demonstrated sensitivity knowledge understanding diverse academic socioeconomic gender gender identity cultural disability ethnic background student serve ; sensitivity knowledge understanding group historically underrepresented group may experienced discrimination 4\ success integrating diversity appropriate major duty outlined job description duty listed district 's hiring policy ; demonstrated equivalent transferable skill working condition environment 1\ typical office environment physical demand 1\ requires sufficient hand-eye-arm coordination use keyboard plus arm/hand movement retrieve work material operate variety general office equipment requires visual acuity read word number requires auditory ability carry conversation phone person san jose/evergreen community college district - classified district represented dedicated talented employee passionate providing student population best educational experience possible district recognizes cultural diversity academic environment promotes academic excellence ; foster cultural racial human understanding ; provides positive role model student creates inclusive supportive educational work environment employee student community serf fall 2017 enrollment approximately 18500 per semester extremely diverse student population hispanic/latino 44 black/african- american 4 asian/pacific islander 32 american indian/native american 0.5 white/caucasian 11 attaining educational goal reflecting 45 - aa degree transfer 4-year college/ university district 's emphasis student success make recognized educational leader state district encourages diverse pool applicant serve colleague existing diverse classified staff consisting 41 hispanic/latino 26 asian/pacific islander 5 black/african american 1 american indian/native american 22 white/caucasian well encouraging application qualified outstanding applicant full application instruction position description visit http //www.edjoin.org/home/jobposting/1079042 copyright ©2017 jobelephant.com inc. right reserved posted free value-added recruitment advertising agency jeid-49be3beb5cf49e46beb2376be8e1a494

In [45]:
print(  encoder.loc[5, 'encoder_job_descriptions']   )

project coordinator san jose/evergreen community college district position 1800072 required document 1\ letter introduction cover letter 2\ resume 3\ copy transcript associate 's degree equivalent department facility & bond program management posting date 07/31/2018 first review date 08/14/2018 position status full-time salary range $ 60632 - $ 74011 annual salary range 96 classified salary schedule fiscal year 2017-2018 starting placement generally step 1 benefit available - classified excellent fringe benefit package includes district paid medical dental vision eap employee assistance plan life insurance employee eligible dependent income protection voluntary plan include supplemental life insurance flexible spending account 403b 457 deferred compensation account classified employee also receive vacation sick leave 18 paid holiday employment start date soon possible position summary program coordinator report director facility bond program district office work schedule 12 month per year ; monday - friday ; 8:00 a.m. 5:00 p.m position represented california school employee association csea chapter 363 position purpose direction director facility bond program management assigned administrator project coordinator performs wide range complex clerical standard advanced office support duty management bond capital outlay program position coordinate various communication activity among administrator department staff vendor consultant public duty responsibilities/specific position 1\ perform appropriate administrative operation support duty assigned supervisor relieve variety technical administrative detail may provide support dept manager staff member 2\ coordinate liaison dept college administrator faculty staff architect engineer consultant ; coordinate activity group preparation project design drawing specification 3\ maintain accurate detailed calendar event due date schedule relate assigned area service ensure proper task activity occur scheduled 4\ prepare meeting agenda minute construction schedule update construction management consultant required project/construction management bond executive meeting 5\ assist onsite coordination move construction project coordinate construction manager faculty staff purchasing personnel necessary 6\ assist preparation departmental report gathering organizing summarizing information variety source including submittals update california community college chancellor 's office fusion database 7\ track project budget activity assist resolving department budget issue problem coordinate timesheets monitor expenditure related bond project 8\ maintain organize facility department network physical information storage system ; ensure required document received logged district record 9\ update construction communication keeping information current community district needed 10\ support vendor outreach effort accordance board policy 11\ prepare compose formal correspondence various agency architect firm college department community required 12\ perform related duty assigned employment standard knowledge 1\ modern office method equipment including computer terminal micro- computer usage word processing application 2\ facility project construction management software system 3\ record keeping principle procedure ; business accounting mathematics ; acceptable business office etiquette 4\ organization time management standard office procedure ability 1\ read interpret apply explain district policy procedure regulation 2\ utilize exceptional organizational skill dealing ambiguity change 3\ establish review work priority ; work independently follow task 4\ compile information write report business correspondence procedure manual using correct english grammar spelling punctuation vocabulary 5\ exhibit strong sense urgency regarding work progress project 6\ effectively communicate interact person diverse background ability 7\ establish maintain cooperative working relationship contacted course work minimum qualification education experience 1\ associate 's degree accredited institution preferably business construction management related field 2\ three year administrative support experience involving heavy public contact primary support individual department preferably public sector 3\ demonstrated sensitivity knowledge understanding diverse academic socioeconomic gender gender identity cultural disability ethnic background student serve ; sensitivity knowledge understanding group historically underrepresented group may experienced discrimination 4\ success integrating diversity appropriate major duty outlined job description duty listed district 's hiring policy ; demonstrated equivalent transferable skill working condition environment 1\ typical office environment physical demand 1\ requires sufficient hand-eye-arm coordination use keyboard plus arm/hand movement retrieve work material operate variety general office equipment requires visual acuity read word number requires auditory ability carry conversation phone person san jose/evergreen community college district - classified district represented dedicated talented employee passionate providing student population best educational experience possible district recognizes cultural diversity academic environment promotes academic excellence ; foster cultural racial human understanding ; provides positive role model student creates inclusive supportive educational work environment employee student community serf fall 2017 enrollment approximately 18500 per semester extremely diverse student population hispanic/latino 44 black/african- american 4 asian/pacific islander 32 american indian/native american 0.5 white/caucasian 11 attaining educational goal reflecting 45 - aa degree transfer 4-year college/ university district 's emphasis student success make recognized educational leader state district encourages diverse pool applicant serve colleague existing diverse classified staff consisting 41 hispanic/latino 26 asian/pacific islander 5 black/african american 1 american indian/native american 22 white/caucasian well encouraging application qualified outstanding applicant full application instruction position description visit http //www.edjoin.org/home/jobposting/1079042 copyright ©2017 jobelephant.com inc. right reserved posted free value-added recruitment advertising agency jeid-49be3beb5cf49e46beb2376be8e1a494