In [11]:
from sklearn.feature_extraction.text import CountVectorizer
from load_data import load_data
import pandas as pd
from jobable.ml_logic.data_keywords import list_of_keywords

In [2]:
job_df = load_data('../data/job_title_des.csv')
job_df

,Unnamed: 0,Job Title,Job Description
0,0,Flutter Developer,We are looking for hire experts flutter develo...
1,1,Django Developer,PYTHON/DJANGO (Developer/Lead) - Job Code(PDJ ...
2,2,Machine Learning,"Data Scientist (Contractor)\n\nBangalore, IN\n..."
3,3,iOS Developer,JOB DESCRIPTION:\n\nStrong framework outside o...
4,4,Full Stack Developer,job responsibility full stack engineer – react...
...,...,...,...
2272,2399,Backend Developer,Job Summary\nPublished on : 26 days ago\nVacan...
2273,2400,Full Stack Developer,business entity cisco umbrella focus cloud-bas...
2274,2401,Network Administrator,Urgently reqd in a college in Mohali\nNetwork ...
2275,2402,Machine Learning,Key Responsibilities: Team leads for small or ...
2276,2403,Full Stack Developer,leslie hindman auctioneer one nation 's leadin...

In [26]:
vectorizer = CountVectorizer(stop_words='english', ngram_range=(1,2), min_df=5)

In [27]:
X = vectorizer.fit_transform(job_df['Job Description'])

In [28]:
X = X.toarray()

In [29]:
X = pd.DataFrame(X, columns=vectorizer.get_feature_names_out())

In [30]:
list_keys = list(list_of_keywords)
list_keys

['qlik',
 'kubeflow',
 'plotly',
 'lasso',
 'data engineer',
 'cohort analysis',
 'classification',
 'lda',
 'fairness',
 'tecton',
 'dbt',
 'superset',
 'google cloud functions',
 'sql queries',
 'statistician',
 'mask r-cnn',
 'cross-functional collaboration',
 'rstudio',
 'vae',
 'google cloud composer',
 'anomaly detection',
 'agile',
 'talend',
 'lightgbm',
 'seaborn',
 'bayesian statistics',
 'fastapi',
 "master's in statistics",
 'standardization',
 'c',
 'credit risk',
 'forecasting',
 'online scoring',
 'speech recognition',
 'azure',
 'azure databricks',
 'pipeline automation',
 'azure synapse',
 'statistical modeling',
 'unsupervised learning',
 'sql server',
 'elk stack',
 'data-driven decision making',
 'databricks',
 'attention to detail',
 'time series analysis',
 'data factory',
 'dagster',
 'cuml',
 'julia',
 'apache spark',
 'google sheets',
 'bigquery',
 'typescript',
 'feature store',
 'bandits',
 'google cloud platform',
 'sqlite',
 'real-time data',
 'large language models',
 'kimball',
 'excel',
 'ci/cd',
 'olap',
 'google professional machine learning engineer',
 'emr',
 'continuous delivery',
 'db2',
 'xgboost',
 'aws athena',
 'mlops engineer',
 'text preprocessing',
 'working with business stakeholders',
 'fbprophet',
 'random forests',
 'eda',
 'stacking',
 'numpy',
 'data ingestion',
 'survival analysis',
 'storm',
 'gcp',
 'data engineer intern',
 'teradata',
 'quant analyst',
 'apache airflow',
 'mentoring',
 'analytics engineer',
 'rapids',
 'pyspark',
 'variational autoencoders',
 'google bigquery',
 'model deployment',
 'ridge regression',
 'communication skills',
 'business intelligence',
 'data lake',
 'stakeholder management',
 'label encoding',
 'cnn',
 "master's degree in data science",
 'matlab',
 'computer vision',
 'snowflake on aws',
 'inferential statistics',
 'vertex ai',
 'clickhouse',
 'recurrent neural networks',
 'p-values',
 'ml pipelines',
 'aws certified machine learning',
 'convex optimization',
 'reporting automation',
 'cassandra',
 'encoder-decoder',
 'object detection',
 'churn analysis',
 'cdc',
 'feature engineering',
 'outlier detection',
 'topic modeling',
 'glove',
 'metrics',
 'hive',
 'mcmc',
 'stemming',
 'gradient boosting',
 'etl developer',
 'descriptive statistics',
 'kpi',
 'outlier handling',
 'data science intern',
 'phd',
 'segmentation',
 'word2vec',
 'ai engineer',
 'attention mechanisms',
 'kanban',
 'google cloud storage',
 'exploratory data analysis',
 'kinesis',
 'bokeh',
 'model registry',
 'fraud detection',
 'encoding categorical variables',
 'gan',
 'leadership',
 'looker',
 'aws emr',
 'prophet',
 'nonparametric tests',
 'reinforcement learning',
 'mode analytics',
 'monte carlo simulation',
 'statsmodels',
 'software engineering',
 'feast',
 "bachelor's in mathematics",
 'trino',
 'project management',
 'one-hot encoding',
 'oracle',
 'aws sagemaker',
 'vertica',
 'business analyst',
 'scipy',
 'tidyverse',
 'pytest',
 'scala',
 'boosting',
 'bootstrapping',
 'stochastic processes',
 'impala',
 'python',
 'microsoft excel',
 'k8s',
 'airflow',
 'logging',
 'customer segmentation',
 'recommendation systems',
 'sklearn',
 'vs code',
 'azure data lake',
 'github',
 'ensemble methods',
 'pca',
 'flask',
 'lime',
 'marketing analytics',
 'clean code',
 'lstm',
 'reporting',
 'hypothesis testing',
 'data analyst',
 'hierarchical clustering',
 'lemmatization',
 'scrum',
 'design patterns',
 'rnn',
 'data scientist',
 'javascript',
 'decision trees',
 'pymc',
 'dimensional modeling',
 'performance metrics',
 'supervised learning',
 'amazon redshift',
 'autoencoders',
 'matplotlib',
 "bachelor's degree in computer science",
 'building apis',
 'k-nearest neighbors',
 'flink',
 'big data engineer',
 't-sne',
 'beam',
 'pricing analytics',
 'recommender systems',
 'naive bayes',
 'responsible ai',
 'catboost',
 'umap',
 'metabase',
 'mle',
 'streaming pipelines',
 'regex',
 'jupyterlab',
 'tokenization',
 'word embeddings',
 'feature importance',
 'ml platforms',
 'kaggle',
 'ad-hoc analysis',
 'stakeholder communication',
 'mlflow',
 'cloud computing',
 'code review',
 "bachelor's in engineering",
 'scikit-learn',
 'mlops',
 'sparklyr',
 'spark streaming',
 'continuous integration',
 'data warehouse',
 'convolutional neural networks',
 'rest apis',
 'model explainability',
 'support vector machines',
 'branching',
 'infrastructure as code',
 'customer analytics',
 'predictive analytics',
 'cloudera',
 'etl',
 'ml orchestration',
 'problem solving',
 'batch processing',
 'circleci',
 'coursera',
 'sampling methods',
 'unit testing',
 'working with product managers',
 'master data management',
 'vba',
 'java',
 'linux',
 'microsoft certified data scientist',
 'bayesian inference',
 'star schema',
 'postgres',
 'gitlab',
 'mysql',
 'index match',
 'kubernetes',
 'data integration',
 'model lifecycle',
 'knn',
 'udacity',
 'databricks certification',
 'terraform',
 'generative adversarial networks',
 'redshift',
 'shap',
 'gru',
 'data lineage',
 'test-driven development',
 'presenting insights',
 'tableau',
 'azure devops',
 'canary deployment',
 'n-grams',
 'tableau prep',
 'data lakehouse',
 'mdm',
 'ranking',
 'self-starter',
 'sql',
 "master's in computer science",
 'pytorch',
 'decision scientist',
 'monitoring',
 'gpt',
 'probability',
 'experimentation platform',
 'image classification',
 'amazon web services',
 'apache flink',
 'stata',
 'model drift',
 'kpis',
 'stitch',
 'regression analysis',
 'cross-validation',
 'a/b testing',
 'regular expressions',
 'prometheus',
 'cudf',
 'pandas',
 'data wrangling',
 'data preprocessing',
 'azure functions',
 'clustering',
 'diagnostic analytics',
 'target encoding',
 'google professional data engineer',
 'kafka',
 'apache beam',
 'mongodb',
 'analytical mindset',
 'risk analytics',
 'github actions',
 'hadoop',
 'dynamodb',
 'data cleaning',
 'operations analytics',
 'descriptive analytics',
 'command line',
 'marketing attribution',
 'prescriptive analytics',
 "bachelor's in statistics",
 'mapreduce',
 'semi-supervised learning',
 'named entity recognition',
 'snowflake',
 'luigi',
 'excel macros',
 'supply chain analytics',
 'spyder',
 'edx',
 'oltp',
 'jenkins',
 'mlr',
 'k-means',
 'quantitative analyst',
 'bagging',
 'jupyter notebook',
 'nlp',
 'tidyr',
 'research scientist',
 'fivetran',
 'shadow deployment',
 'pull requests',
 'feature scaling',
 'inmon',
 'linear algebra',
 'leading projects',
 'aws lambda',
 'gcs',
 'data normalization',
 'transformers',
 'rmarkdown',
 'data drift',
 'production machine learning',
 'dimensionality reduction',
 'funnel analysis',
 'optimization',
 'datacamp',
 'markov chain monte carlo',
 'redis',
 'model serving',
 'data transformation',
 'financial analytics',
 'microservices',
 'contextual bandits',
 'experiment tracking',
 'snowflake schema',
 'tensorflow',
 'elastic net',
 'model selection',
 'aws glue',
 'self-supervised learning',
 'looker studio',
 'opencv',
 'collaborative filtering',
 'yolo',
 'ml engineer',
 'data storytelling',
 'elasticsearch',
 'dbt cloud',
 'critical thinking',
 'data.table',
 'containers',
 'aws s3',
 'neural networks',
 'airflow on spark',
 'qlik sense',
 'maximum likelihood estimation',
 'ray',
 'sequence models',
 'c#',
 'data quality',
 'prefect',
 'anova',
 'model monitoring',
 'data pipelines',
 'dashboards',
 'denormalization',
 'microsoft azure',
 'dplyr',
 'deep learning',
 'informatica',
 'integration testing',
 'strong communication',
 'sentiment analysis',
 'gcp dataflow',
 'c++',
 'bi analyst',
 'machine learning engineer',
 'spark sql',
 'change data capture',
 'text classification',
 'content-based filtering',
 'kibana',
 'var',
 'gcp dataproc',
 'batch scoring',
 'probability distributions',
 'shiny',
 'pymc4',
 'llms',
 'feature extraction',
 'senior data scientist',
 'natural language processing',
 'analytics intern',
 'snowflake on gcp',
 'elt',
 'qlikview',
 'snowflake on azure',
 'version control',
 'logistics optimization',
 'working with engineers',
 'spark',
 'bash',
 'product analytics',
 'experimentation',
 'azure ml',
 'serverless',
 'normalization',
 'pivot tables',
 'git',
 'hyperparameter tuning',
 'keras',
 'ssis',
 'excel dashboards',
 'tdd',
 'unittest',
 'linear regression',
 'recommendation engines',
 'shell scripting',
 'altair',
 'hdfs',
 'tableau server',
 'power bi',
 'seq2seq',
 'vlookup',
 'data modeling',
 'grafana',
 'svm',
 'bert',
 'dask',
 'postgresql',
 'jupyter',
 'django',
 'dbscan',
 'applied scientist',
 'missing data imputation',
 'data munging',
 'apache kafka',
 'aws certified data analytics',
 'r',
 'sequence-to-sequence',
 'neo4j',
 'pymc3',
 'sas',
 'ggplot2',
 'ggplot',
 'explainable ai',
 'ner',
 'sarima',
 'jax',
 'fast learner',
 'redash',
 'time series forecasting',
 'caret',
 'docker',
 'hortonworks',
 'confidence intervals',
 'stop word removal',
 'aws',
 'logistic regression',
 'regression',
 'data governance',
 'arima',
 'presto',
 'feature selection',
 'unix',
 'bitbucket',
 's3',
 'growth analytics',
 'google data studio',
 'dbt core',
 'xai',
 'mariadb']

In [31]:
X

,00,00 00,00 000,00 10,00 100,00 12,00 15,00 150,00 18,00 20,...,yrs relevant,yrs salary,yrs yrs,zabbix,zend,zend framework,zero,zone,zones,zoom
0,2,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2272,0,0,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
2273,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2274,2,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2275,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2276,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [33]:
result = dict()

In [ ]:
for kw in list_keys:
    if kw in X.columns:
        result[kw] = X[kw].sum()

In [42]:
list_count = []

In [46]:
list_count = result.items()
list_count

dict_items([('classification', 33), ('fairness', 5), ('sql queries', 26), ('anomaly detection', 16), ('agile', 665), ('standardization', 8), ('forecasting', 17), ('azure', 264), ('unsupervised learning', 5), ('sql server', 187), ('elk stack', 14), ('databricks', 5), ('apache spark', 5), ('typescript', 85), ('sqlite', 30), ('excel', 85), ('emr', 15), ('continuous delivery', 50), ('db2', 32), ('numpy', 29), ('gcp', 73), ('teradata', 24), ('mentoring', 75), ('pyspark', 6), ('communication skills', 457), ('business intelligence', 19), ('cnn', 11), ('matlab', 16), ('computer vision', 52), ('cassandra', 51), ('feature engineering', 10), ('metrics', 69), ('hive', 28), ('phd', 28), ('segmentation', 16), ('kanban', 27), ('kinesis', 9), ('leadership', 206), ('reinforcement learning', 7), ('software engineering', 165), ('project management', 67), ('oracle', 237), ('business analyst', 7), ('scipy', 9), ('scala', 49), ('boosting', 7), ('python', 973), ('k8s', 12), ('logging', 42), ('github', 136), ('flask', 63), ('clean code', 35), ('lstm', 10), ('reporting', 174), ('data analyst', 11), ('scrum', 177), ('design patterns', 219), ('rnn', 5), ('data scientist', 71), ('javascript', 1456), ('decision trees', 9), ('performance metrics', 7), ('matplotlib', 7), ('building apis', 5), ('recommender systems', 5), ('naive bayes', 5), ('kaggle', 6), ('cloud computing', 33), ('code review', 45), ('continuous integration', 178), ('data warehouse', 18), ('rest apis', 85), ('branching', 18), ('predictive analytics', 7), ('etl', 46), ('problem solving', 439), ('circleci', 7), ('unit testing', 128), ('vba', 8), ('java', 989), ('linux', 425), ('postgres', 51), ('gitlab', 46), ('mysql', 557), ('kubernetes', 207), ('data integration', 12), ('terraform', 79), ('redshift', 19), ('tableau', 26), ('azure devops', 33), ('ranking', 13), ('sql', 777), ('pytorch', 42), ('monitoring', 396), ('probability', 24), ('kpis', 7), ('prometheus', 26), ('pandas', 26), ('azure functions', 7), ('clustering', 21), ('kafka', 80), ('mongodb', 229), ('hadoop', 85), ('dynamodb', 35), ('data cleaning', 6), ('command line', 15), ('mapreduce', 9), ('snowflake', 8), ('oltp', 5), ('jenkins', 236), ('nlp', 70), ('aws lambda', 15), ('optimization', 238), ('redis', 81), ('microservices', 133), ('tensorflow', 62), ('opencv', 14), ('yolo', 5), ('ml engineer', 5), ('elasticsearch', 49), ('critical thinking', 18), ('containers', 61), ('aws s3', 5), ('neural networks', 22), ('data quality', 25), ('data pipelines', 14), ('dashboards', 23), ('microsoft azure', 15), ('deep learning', 86), ('informatica', 14), ('integration testing', 33), ('strong communication', 56), ('sentiment analysis', 7), ('kibana', 18), ('version control', 159), ('spark', 72), ('bash', 66), ('experimentation', 14), ('serverless', 29), ('git', 598), ('keras', 30), ('ssis', 19), ('tdd', 35), ('shell scripting', 50), ('hdfs', 8), ('power bi', 8), ('data modeling', 37), ('grafana', 33), ('svm', 13), ('bert', 8), ('postgresql', 114), ('django', 368), ('sas', 22), ('jax', 8), ('fast learner', 13), ('docker', 250), ('aws', 669), ('logistic regression', 8), ('regression', 47), ('unix', 131), ('bitbucket', 61), ('s3', 65), ('mariadb', 6)])

In [49]:
sorted(list_count, key = lambda item: item[1], reverse=True)

[('javascript', 1456),
 ('java', 989),
 ('python', 973),
 ('sql', 777),
 ('aws', 669),
 ('agile', 665),
 ('git', 598),
 ('mysql', 557),
 ('communication skills', 457),
 ('problem solving', 439),
 ('linux', 425),
 ('monitoring', 396),
 ('django', 368),
 ('azure', 264),
 ('docker', 250),
 ('optimization', 238),
 ('oracle', 237),
 ('jenkins', 236),
 ('mongodb', 229),
 ('design patterns', 219),
 ('kubernetes', 207),
 ('leadership', 206),
 ('sql server', 187),
 ('continuous integration', 178),
 ('scrum', 177),
 ('reporting', 174),
 ('software engineering', 165),
 ('version control', 159),
 ('github', 136),
 ('microservices', 133),
 ('unix', 131),
 ('unit testing', 128),
 ('postgresql', 114),
 ('deep learning', 86),
 ('typescript', 85),
 ('excel', 85),
 ('rest apis', 85),
 ('hadoop', 85),
 ('redis', 81),
 ('kafka', 80),
 ('terraform', 79),
 ('mentoring', 75),
 ('gcp', 73),
 ('spark', 72),
 ('data scientist', 71),
 ('nlp', 70),
 ('metrics', 69),
 ('project management', 67),
 ('bash', 66),
 ('s3', 65),
 ('flask', 63),
 ('tensorflow', 62),
 ('containers', 61),
 ('bitbucket', 61),
 ('strong communication', 56),
 ('computer vision', 52),
 ('cassandra', 51),
 ('postgres', 51),
 ('continuous delivery', 50),
 ('shell scripting', 50),
 ('scala', 49),
 ('elasticsearch', 49),
 ('regression', 47),
 ('etl', 46),
 ('gitlab', 46),
 ('code review', 45),
 ('logging', 42),
 ('pytorch', 42),
 ('data modeling', 37),
 ('clean code', 35),
 ('dynamodb', 35),
 ('tdd', 35),
 ('classification', 33),
 ('cloud computing', 33),
 ('azure devops', 33),
 ('integration testing', 33),
 ('grafana', 33),
 ('db2', 32),
 ('sqlite', 30),
 ('keras', 30),
 ('numpy', 29),
 ('serverless', 29),
 ('hive', 28),
 ('phd', 28),
 ('kanban', 27),
 ('sql queries', 26),
 ('tableau', 26),
 ('prometheus', 26),
 ('pandas', 26),
 ('data quality', 25),
 ('teradata', 24),
 ('probability', 24),
 ('dashboards', 23),
 ('neural networks', 22),
 ('sas', 22),
 ('clustering', 21),
 ('business intelligence', 19),
 ('redshift', 19),
 ('ssis', 19),
 ('data warehouse', 18),
 ('branching', 18),
 ('critical thinking', 18),
 ('kibana', 18),
 ('forecasting', 17),
 ('anomaly detection', 16),
 ('matlab', 16),
 ('segmentation', 16),
 ('emr', 15),
 ('command line', 15),
 ('aws lambda', 15),
 ('microsoft azure', 15),
 ('elk stack', 14),
 ('opencv', 14),
 ('data pipelines', 14),
 ('informatica', 14),
 ('experimentation', 14),
 ('ranking', 13),
 ('svm', 13),
 ('fast learner', 13),
 ('k8s', 12),
 ('data integration', 12),
 ('cnn', 11),
 ('data analyst', 11),
 ('feature engineering', 10),
 ('lstm', 10),
 ('kinesis', 9),
 ('scipy', 9),
 ('decision trees', 9),
 ('mapreduce', 9),
 ('standardization', 8),
 ('vba', 8),
 ('snowflake', 8),
 ('hdfs', 8),
 ('power bi', 8),
 ('bert', 8),
 ('jax', 8),
 ('logistic regression', 8),
 ('reinforcement learning', 7),
 ('business analyst', 7),
 ('boosting', 7),
 ('performance metrics', 7),
 ('matplotlib', 7),
 ('predictive analytics', 7),
 ('circleci', 7),
 ('kpis', 7),
 ('azure functions', 7),
 ('sentiment analysis', 7),
 ('pyspark', 6),
 ('kaggle', 6),
 ('data cleaning', 6),
 ('mariadb', 6),
 ('fairness', 5),
 ('unsupervised learning', 5),
 ('databricks', 5),
 ('apache spark', 5),
 ('rnn', 5),
 ('building apis', 5),
 ('recommender systems', 5),
 ('naive bayes', 5),
 ('oltp', 5),
 ('yolo', 5),
 ('ml engineer', 5),
 ('aws s3', 5)]

In [40]:
pd.DataFrame(result, columns=result.keys())

ValueError: If using all scalar values, you must pass an index